spring:
  application:
    name: qkmall-member
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
  jackson:
    date-format: yyyy-MM-DD HH:mm:ss
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/code_member?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: admin
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
logging:
  level:
    com.qkmall: debug
server:
  port: 8015
